version: "3"
services:
  nodejs: #docker run -it -v ${PWD}:/work -w /work -p 5002:5000 lera/nodejs:1.0.1 /bin/sh
    container_name: nodejs
    image: lera/nodejs:1.0.1
    build: ./nodejs
    working_dir: /work
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./nodejs/src/:/work
    ports:
      - 5002:5000
